### ISSUE TITLE
User-supplied update for Cyrillic keyboard

### ISSUE THREAD

**Issue by jackiew1** [geek1011/kobopatch-patches#23]
@geek1011, I don't know whether you saw this but an MR user has posted an update if you wanted to include it in the standard pack for next time. 
MR:post-3894655

I think we need more users like this :)

**Comment by geek1011** [comment]
> @geek1011, I don't know whether you saw this but an MR user has posted an update if you wanted to include it in the standard pack for next time.

Yes, I noticed that. I'm probably going to include it, as it has been requested a few times, and is well written.

> I think we need more users like this :)

I agree that was a pleasant surprise. Especially that the offsets and string lengths were correct, and that they had the thoughtfulness to put everything in order by offset (that was one of the main reasons I didn't want to rewrite all of the original ones from scratch). Also, they used a good find string instead of just putting something random from around the area which may not have stayed unique.

**Comment by jackiew1** [comment]
@geek1011 
Updated Greek keyboard posted by Bald Eagle here https://www.mobileread.com/forums/showpost.php?p=3895481&postcount=125

**Comment by geek1011** [comment]
Yep. I'll add them for the next release. I'm probably going to put them in `geoffr.yaml` with a note about who updated it. I've also sent Bald Eagle a PM about this.

**Comment by geek1011** [comment]
@jackie_w, I've sent a PM to Semwize (it's also been forwarded to you too) about becoming a collaborator on this repository, as he's correctly updated multiple patches now (and without assistance, too).
