### ISSUE TITLE
GeoffR's "Custom font sizes"

### ISSUE THREAD

**Issue by jackiew1** [geek1011/kobopatch-patches#30]
Semwize posted a new version for 4.18. MR:post-3897542

I asked whether he knew how to add the LibraH2O stuff. Answer is no.

**Comment by ezel3** [comment]
Hmm, seems I reinvented the wheel. I also made a new version before I saw this one. But if someone is interested, I also documented the hex patterns (see 'Find hex string' in the zip) so it is much easier to locate the places that must be altered. Hope this is of some use for future patches.
[custom_font_sizes.zip](https://github.com/geek1011/kobopatch-patches/files/3775065/custom_font_sizes.zip)

**Comment by geek1011** [comment]
So, it seems the Libra H2O uses the same values as the Clara. This can be determined based on my [research](https://gist.github.com/geek1011/613b34c23f026f7c39c50ee32f5e167e) (those multi-layer device codenames are a bit annoying) and tracing the complicated (because of GCC optimization) set of branches on Device::is*. I've updated Semwize's updated patch with this info.
